apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-niwr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-niwr
    app.kubernetes.io/part-of: tkrw-pr714-0075-0069-app
  name: devfile-sample-niwr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-niwr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-niwr
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0069-tenant/tkrw-pr714-0075-0069-app/devfile-sample-niwr@sha256:2584d155a60fcee223b098650f9479d51087e56f55b4c56ad12c730c8d4365c3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
