apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-niwr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0069-tenant/tkrw-pr714-0075-0069-app/devfile-sample-niwr@sha256:2584d155a60fcee223b098650f9479d51087e56f55b4c56ad12c730c8d4365c3
        name: my-nodejs
        resources: {}
status: {}
